version: "3"
services:
    metric-service:
        profiles: ["with_gpu"]
        build: ./services/metric
        container_name: thinking_metric
        restart: no
        environment:
            ERROR_LOG: /app/log/error.log
            LOG_LEVEL: info
            PYTHONUNBUFFERED: "TRUE"
        volumes:
            - ./artifacts/log/metric:/app/log
            - ./services/metric:/app
            - ./src:/app/src
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          capabilities: [gpu]
    entry-service:
        build: ./services/entrypoint
        container_name: thinking_entrypoint
        restart: no
        depends_on:
            - embedding-service
            - hippocampus-service
        environment:
            ERROR_LOG: /app/log/error.log
            LOG_LEVEL: info
            PYTHONUNBUFFERED: "TRUE"
        ports:
            - 8000:8000
        volumes:
            - ./artifacts/log/entrypoint:/app/log
            - ./services/entrypoint:/app
            - ./src:/app/src
