FROM python:3.10

RUN apt update && apt install python3-pip git -y
RUN pip3 install --upgrade pip

RUN pip3 install --upgrade jax[cpu]
COPY ./requirements.txt /app/requirements.txt

WORKDIR /app
RUN pip3 install --no-cache-dir -r requirements.txt
CMD ["python3", "-m", "debugpy", "--listen", "0.0.0.0:5678", "tasks/benchmark.py"]