version: "3"
services:
    jax-gpu-service:
        profiles: ["jax-gpu"]
        build:
            dockerfile: ./Dockerfile
            context: .
        container_name: thinking-gpu
        restart: no
        volumes:
            - ./artifacts/log/:/app/log
            - ./artifacts/cache:/app/cache
            - ./artifacts/experiments:/app/experiments
            - ./humn:/app/humn
            - ./core:/app/core
            - ./jax_onehot:/app/jax_onehot
            - ./tasks:/app/tasks
        environment:
            - ERROR_LOG=/app/log/error.log
            - LOG_LEVEL=info
            - PYTHONUNBUFFERED=TRUE
            - TF_CPP_MIN_LOG_LEVEL=0
        env_file:
            - ./secrets.env
        ports:
            - "127.0.0.1:5678:5678"
        networks:
            - app_network
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          count: 1
                          capabilities: [gpu]
    jax-cpu-service:
        profiles: ["jax-cpu"]
        build:
            dockerfile: ./Dockerfile.nogpu
            context: .
        container_name: thinking-cpu
        restart: no
        volumes:
            - ./artifacts/log:/app/log
            - ./artifacts/cache:/app/cache
            - ./artifacts/experiments:/app/experiments
            - ./humn:/app/humn
            - ./core:/app/core
            - ./jax_onehot:/app/jax_onehot
            - ./tasks:/app/tasks
        environment:
            - ERROR_LOG=/app/log/error.log
            - LOG_LEVEL=info
            - PYTHONUNBUFFERED=TRUE
            - TF_CPP_MIN_LOG_LEVEL=0
        env_file:
            - ./secrets.env
        ports:
            - "127.0.0.1:5678:5678"
        networks:
            - app_network
    api-call-service:
        profiles: ["api-call"]
        build:
            dockerfile: ./Dockerfile.pure_python
            context: .
        container_name: thinking-api-call
        restart: no
        volumes:
            - ./artifacts/log:/app/log
            - ./artifacts/cache:/app/cache
            - ./artifacts/experiments:/app/experiments
            - ./humn:/app/humn
            - ./core:/app/core
            - ./llm:/app/llm
            - ./tasks:/app/tasks
        environment:
            - ERROR_LOG=/app/log/error.log
            - LOG_LEVEL=info
            - PYTHONUNBUFFERED=TRUE
            - TF_CPP_MIN_LOG_LEVEL=0
        env_file:
            - ./secrets.env
        ports:
            - "127.0.0.1:5678:5678"
        networks:
            - app_network
    torch-cpu-service:
        profiles: ["torch-cpu"]
        build:
            dockerfile: ./Dockerfile.nogpu_torch
            context: .
        container_name: thinking-cpu-torch
        restart: no
        volumes:
            - ./artifacts/log:/app/log
            - ./artifacts/cache:/app/cache
            - ./artifacts/experiments:/app/experiments
            - ./humn:/app/humn
            - ./core:/app/core
            - ./jax_onehot:/app/jax_onehot
            - ./tasks:/app/tasks
        environment:
            - ERROR_LOG=/app/log/error.log
            - LOG_LEVEL=info
            - PYTHONUNBUFFERED=TRUE
            - TF_CPP_MIN_LOG_LEVEL=0
        env_file:
            - ./secrets.env
        ports:
            - "127.0.0.1:5678:5678"
        networks:
            - app_network
networks:
    app_network:
        driver: bridge
