FROM python:3.10

RUN apt update && apt install python3-pip -y
RUN pip3 install --upgrade pip

# build JAX from source
RUN pip3 install --upgrade jax[cpu]
COPY ./requirements.txt /app/requirements.txt

WORKDIR /app
RUN pip3 install -r requirements.txt
CMD ["python3", "main.py"]